# Tox configuration file using uv as the backend runner
# Read more under https://tox.wiki/

[tox]
minversion = 4.0
envlist = default

[testenv]
description = Invoke pytest to run automated tests
extras = testing
deps = twine
commands =
    pytest {posargs}

[testenv:typecheck]
deps = mypy
description = Run static type checking with mypy
commands =
    mypy src/

[testenv:lint]
description = Perform static analysis and style checks
deps = ruff
skip_install = True
commands =
    ruff check {posargs:.}
    ruff format --check {posargs:.}

[testenv:{build,clean}]
description =
    build: Build the package
    clean: Remove old distribution files
deps = build
skip_install = True
commands =
    clean: python -c 'import shutil; [shutil.rmtree(p, True) for p in ("build", "dist", "docs/_build")]'
    clean: python -c 'import pathlib, shutil; [shutil.rmtree(p, True) for p in pathlib.Path("src").glob("*.egg-info")]'
    build: python -m build {posargs}

[testenv:{docs,doctests,linkcheck}]
description =
    docs: Invoke sphinx-build to build the docs
    doctests: Invoke sphinx-build to run doctests
    linkcheck: Check for broken links in the documentation
deps =
    -r {toxinidir}/docs/requirements.txt
setenv =
    DOCSDIR = {toxinidir}/docs
    BUILDDIR = {toxinidir}/docs/_build
    docs: BUILD = html
    doctests: BUILD = doctest
    linkcheck: BUILD = linkcheck
commands =
    sphinx-apidoc -f -o "{env:DOCSDIR}/api" src/
    sphinx-build --color -b {env:BUILD} -d "{env:BUILDDIR}/doctrees" "{env:DOCSDIR}" "{env:BUILDDIR}/{env:BUILD}" {posargs}

[testenv:publish]
description =
    Publish the package you have been developing to a package index server.
skip_install = True
deps = twine
commands =
    python -m twine upload {posargs:dist/*}
